name: pharmeasy
description: PharmEasy is an innovative drug delivery and consultation app designed to bring quality healthcare right to your doorstep. 

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.0.6

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  google_fonts: ^6.1.0
  carousel_slider: ^5.0.0
  firebase_auth: ^4.14.0
  firebase_core: ^2.22.0
  flutter_rating_stars: ^1.0.3+4
  google_nav_bar: ^5.0.6
  buttons_tabbar: ^1.3.8
  flutter_slidable: ^3.0.1
  dotted_decoration: ^2.0.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logos/pharmeasy-logo.png"
  min_sdk_android: 19

flutter:
  uses-material-design: true

  assets:
    - assets/images/pharmacies/
    - assets/images/banners/
    - assets/images/medicines/
    - assets/images/logos/
    - assets/images/categories/
