// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1p3PWG70kJ8oCAQnZKxlHBJc_QQT6Hps',
    appId: '1:937758458478:web:a72a554a755d9e9244dc7f',
    messagingSenderId: '937758458478',
    projectId: 'pharmeasy-481a4',
    authDomain: 'pharmeasy-481a4.firebaseapp.com',
    storageBucket: 'pharmeasy-481a4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWi6DSe22P7AsaId55Bccjy07YK9itagQ',
    appId: '1:937758458478:android:dc0b82b47aa14c2544dc7f',
    messagingSenderId: '937758458478',
    projectId: 'pharmeasy-481a4',
    storageBucket: 'pharmeasy-481a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXWCYA5RcImRI5W4wxUKwa5NWdtoVtvRE',
    appId: '1:937758458478:ios:68eb94968a1e523a44dc7f',
    messagingSenderId: '937758458478',
    projectId: 'pharmeasy-481a4',
    storageBucket: 'pharmeasy-481a4.appspot.com',
    iosBundleId: 'com.example.pharmeasy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXWCYA5RcImRI5W4wxUKwa5NWdtoVtvRE',
    appId: '1:937758458478:ios:cf7f2a6dc5fa175b44dc7f',
    messagingSenderId: '937758458478',
    projectId: 'pharmeasy-481a4',
    storageBucket: 'pharmeasy-481a4.appspot.com',
    iosBundleId: 'com.example.pharmeasy.RunnerTests',
  );
}
